### ISSUE TITLE
convertor.py can't locate attribute: 'model_config'

### ISSUE THREAD

**Issue by paragraph14** [DigitalMediaProfessionals/dv-sdk#11]
I challenged the network conversion using convertor.py.

```bash
python convertor.py vae_cnn_mnist.ini
```

```vae_cnn_mnist.ini
;vae_cnn_mnist.ini
[INPUT]
name = vae_cnn_mnist
definition = vae_cnn_mnist.h5
origin = keras

[OUTPUT]
output_folder = ./
generate_source = 1
generate_doxy 	= 1
generate_dot 	= 1

[OPTIONAL]
verbose = 1
graphviz_path = C:/Program Files (x86)/Graphviz2.38/bin
```

The following error was obtained.

```bash
Traceback (most recent call last):
  File "convertor.py", line 134, in <module>
    custom_layer, dim_override)
  File "C:\Project\dv-sdk\tool\cnn_convertor\cnn_parser.py", line 37, in parse_network
    parser_keras.parse_keras_network(network, network_data)
  File "C:\Project\dv-sdk\tool\cnn_convertor\parser_keras.py", line 600, in parse_keras_network
    netdef = keras_net.attrs['model_config']
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\Project\dv-sdk\tool\.venv\lib\site-packages\h5py\_hl\attrs.py", line 60, in __getitem__
    attr = h5a.open(self._id, self._e(name))
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5a.pyx", line 77, in h5py.h5a.open
KeyError: "Can't open attribute (can't locate attribute: 'model_config')"
```

I confirmed the attribute of the network.

```bash
>>> model_ok = h5py.File('test.ini.h5')
>>> model_ng = h5py.File('vae_cnn_mnist.h5')
>>> list(model_ok.attrs.keys())
['backend', 'keras_version', 'model_config']
>>> list(model_ng.attrs.keys())
['backend', 'keras_version', 'layer_names']
```

Network is Keras's VAE sample. 
https://github.com/keras-team/keras/blob/master/examples/variational_autoencoder_deconv.py

**Comment by YuyaKobayashi** [comment]
Hi,  paragraph14-san,

That is because `vae_cnn_mnist.h5` is saved by `save_weights()` but the tool accepts model saved by `model.save()`, as described in [wiki](https://github.com/DigitalMediaProfessionals/dv-sdk/wiki/Input-Files-to-the-DMP-tool#keras).

Thank you,
Kobayashi

**Comment by paragraph14** [comment]
Thank you.
